# Generated by Django 4.0.3 on 2023-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Seller', 'Seller')], default='Client', max_length=30),
        ),
    ]
